[coupled_test]
if_type = "izhikevich"
iterations = 10000
input_voltage = 25.0
pre_dt = 0.5
post_dt = 0.5
pre_alpha_init = 0.01
pre_beta_init = 0.25
pre_w_init = 20.0
pre_v_reset = -50.0
pre_d_init = 2.0
filename = "coupled tests/bursting_in_tonic_out.txt"
input_equation = "sign * mp + 65"
