[simulation]
num_rows = 20
num_cols = 20
iterations = 1000 # if changing dt change iterations accordingly
dt = 0.001
radius = 2
# excitatory_chance = 0.8
output_tag = "eeg_like"
output_type = "binary averaged"
# tau_m = 50.0
lif_type = "adaptive exponential"
input_equation = """
    s * m + 200. + r * (n^3 * 300.) 
""" # maybe n^3
# random_volt_initialization = true

# optimizable parameters:

# fixed parameter equation restraints 
# likely will have to compensate for dt being so small by scaling 
# parameters by larger amounts

# and maybe these probably not for now
# tau_m
# a
# b
# bayesian_std
# tref
# lif_type
# excitatory_chance
