[lattice_simulation]
num_rows = 10
num_cols = 10
radius = 1
tag = "stdp_lattice"
output_type = "grid"
if_type = "izhikevich"
random_volt_initialization = true
do_stdp = true
iterations = 1000
input_equation = """
    (sign * mp + 65) / 15.
"""
