[lattice_simulation]
num_rows = 20
num_cols = 20
radius = 2
dt = 0.1
iterations = 300000 # five minutes simulated
# when evaluating make sure to account for timeframe
tag = "large_timeframe"
output_type = "grid"
if_type = "izhikevich"
random_volt_initialization = true
# do_stdp = true
# weight_init = 1.0
# weight_min = 0.8
# weight_max = 1.2
# different weight caps and mins should be tested
a_plus = 0.5
a_minus = 0.5
input_equation = """
    (sign * mp + 65) / 15.
"""
