[lattice_simulation]
num_rows = 10
num_cols = 10
radius = 1
tag = "stdp_lattice"
output_type = "grid"
if_type = "izhikevich"
random_volt_initialization = true
do_stdp = true
weight_init = 1.0
# different weight caps and mins should be tested
a_plus = 0.5
a_minus = 0.5
iterations = 200
input_equation = """
    (sign * mp + 65) / 15.
"""
