[coupled_hodgkin_huxley]
post_AMPA = true
# post_GABAa = true
# post_GABAb = true
# post_NMDA = true
pre_dt = 0.01
post_dt = 0.01
input_voltage = 50.0
iterations = 10000
filename = "coupled_hodgkin_huxley.csv"
bayesian = false
full = true
