[coupled_test]
if_type = "izhikevich"
iterations = 10000
input_current = 25.0
pre_dt = 0.1
post_dt = 0.1
pre_v_init = -65.0
post_v_init = -65.0
# post_alpha_init = 0.01
# pre_alpha_init = 0.01
# post_beta_init = 0.5
# pre_beta_init = 0.5
# pre_AMPA = true
post_AMPA = true
full = true
filename = "output/izhikevich_neurotransmitter.csv"
