[coupled_test]
if_type = "izhikevich"
iterations = 10000
input_current = 25.0
pre_dt = 0.1
post_dt = 0.1
pre_v_init = -65.0
post_v_init = -65.0

pre_w_init = 10.0
post_w_init = 10.0

pre_c_m = 100.0
post_c_m = 100.0

# pre_c_m = 10.0
# post_c_m = 10.0

# pre_tau_m = 10.0
# post_tau_m = 10.0

# post_alpha_init = 0.01
# pre_alpha_init = 0.01
# post_beta_init = 0.5
# pre_beta_init = 0.5
pre_AMPA = true
post_AMPA = true
verbose = true
pre_receptor_occupancy_default = 0.8
post_receptor_occupancy_default = 0.8

# filename = "output/izhikevich_neurotransmitter.csv"
filename = "output/izhikevich_coupled.csv"
