[coupled_test]
if_type = "izhikevich"
iterations = 10000
input_voltage = 25.0
pre_dt = 0.5
post_dt = 0.5
pre_v_init = -65.0
post_v_init = -65.0
current = true
filename = "output/gap_junction_test.csv"
input_equation = "-sign * mp"
