[lattice_simulation]
# tag = "output/lattice_test"
# tag = "output/lattice_test_grid"
tag = "output/refactor_lattice_test_grid"
# tag = "output/lattice_test_averaged"
# output_type = "eeg"
output_type = "grid"
# output_type = "averaged"
if_type = "izhikevich"

num_rows = 20
num_cols = 20
radius = 2

v_init = -65.0
random_volt_initialization = true
iterations = 10000

# do_stdp = true
# weight_init = 10.0
# weight_min = 10.0
# weight_max = 10.0

# could also set c_m and tau_m to 
gap_condutance_init = 1.0

bayesian = true
bayesian_std = 1.0
averaged = true

# current = true
# input_equation = """
#     sign * mp
# """
# # input_equation = """
# #     (sign * mp + 65) / 15.
# # """
