[lattice_simulation]
num_rows = 20
num_cols = 20
radius = 2
tag = "lattice_eeg_test"
output_type = "grid"
if_type = "izhikevich"
random_volt_initialization = true
iterations = 10000
current = true
input_equation = """
    sign * mp
"""
