[coupled_spike_train_test]
if_type = "izhikevich"
iterations = 10000
input_current = 25.0
poisson_firing_rate = 30.0
poisson_v_th = 30.0
poisson_v_resting = 0.0
poisson_decay = 10000.0
poisson_clearance_constant = 0.1
poisson_dt = 0.1
pre_dt = 0.1
post_dt = 0.1
pre_v_init = -65.0
post_v_init = -65.0

pre_w_init = 10.0
post_w_init = 10.0

pre_c_m = 100.0
post_c_m = 100.0

pre_gap_conductance = 10.0
post_gap_conductance = 10.0

# pre_c_m = 10.0
# post_c_m = 10.0

# pre_tau_m = 10.0
# post_tau_m = 10.0

# post_alpha_init = 0.01
# pre_alpha_init = 0.01
# post_beta_init = 0.5
# pre_beta_init = 0.5
poisson_AMPA = true
pre_AMPA = true
post_AMPA = true
verbose = true
do_receptor_kinetics = false
pre_receptor_occupancy_default = 0.8
post_receptor_occupancy_default = 0.8

filename = "output/poisson_coupled.csv"
