[stdp_test]
if_type = "izhikevich"
iterations = 10000
weight_init = 1.0
weight_max = 2.0
weight_min = 0.0
weight_std = 0.1
n = 2
input_voltage = 30.0
filename = "results/current_stdp.csv"
bayesian_std = 0.3
current = true
input_equation = "-sign * mp"
