[lattice_simulation]
num_rows = 10
num_cols = 10
radius = 2
tag = "lattice_speed_test"
output_type = "grid"
if_type = "adaptive exponential"
random_volt_initialization = true
iterations = 200
input_equation = """
    (sign * mp + 100 + rd * (nc^2 * 200)) / 15.
"""
