program = _{ SOI ~ "\n"* ~ (stmt ~ "\n"+) * ~ stmt? ~ EOI }

stmt = _{ expr }

expr = {
      assgmtExpr
    | monadicExpr
    | dyadicExpr
    | terms
}

monadicExpr = { verb ~ expr }

dyadicExpr = { (monadicExpr | terms) ~ verb ~ expr }

assgmtExpr = { ident ~ "=" ~ expr }

terms = { term+ }

// add functions
term = _{ function | number | ident | "(" ~ expr ~ ")" }

verb = {
  	"*" | "/" | "+" | "-" | "^" 
}

integer = @{ ASCII_DIGIT+ }
decimal = @{ ASCII_DIGIT+ ~ "." ~ ASCII_DIGIT* }
number = @{ integer | decimal }

ident = @{ ASCII_ALPHA ~ (ASCII_ALPHANUMERIC | "_")* }

args = { 
	(expr | function | ident | number)? ~ (" "* ~ "," ~ " "* ~ (expr | function | ident | number))* ~ ","? 
}
function = { ident ~ ("(" ~ args ~ ")") }

WHITESPACE = _{ " " | "\t" }

COMMENT = _{ "//" ~ (!"\n" ~ ANY)* }
